config/routes.rb
Rails.application.routes.draw do
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]

  resource :session, controller: "sessions", only: [:create]

  resources :users, controller: "users", only: [:create] do
    resource(
      :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update],
    )
  end

  get "/sign_in" => "sessions#new", as: "sign_in"
  delete "/sign_out" => "sessions#destroy", as: "sign_out"
  get "/sign_up" => "users#new", as: "sign_up"

  resources :members, only: [:index, :show, :new, :create]

  resources :payments, only: [:index, :create] do
    collection do
      patch :update_statuses
    end
  end

  root to: "welcome#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/member.rb
class Member < ApplicationRecord
  has_many :payments, dependent: :destroy

  enum membership_type: {
    active: 0,
    passive: 1,
    family: 2,
    dgi: 3,
    ki_doin: 4,
  }

  validates :first_name, :middle_name, :last_name, presence: true

  def name
    [first_name, middle_name, last_name].join(" ")
  end

  def create_pending_payment
    payments.create!(status: :pending)
  end
end

app/models/member_filters.rb
class MemberFilters
  def initialize(filters:)
    @filters = filters
  end

  def apply_filters(members)
    [
      :apply_membership_type_filter,
      :apply_minimum_age_filter,
    ].reduce(members) do |acc, method|
      send(method, acc)
    end
  end

  private

  def apply_membership_type_filter(members)
    return members unless @filters["membership_type"].present?

    members.where(
      membership_type: @filters.fetch("membership_type")
    )
  end

  def apply_minimum_age_filter(members)
    return members unless @filters["minimum_age"].present?

    minimum_age = @filters.fetch("minimum_age")
    members = members.where(
      "members.date_of_birth > now() - interval '? year'",
      minimum_age.to_i,
    )
  end
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :member

  enum status: {
    pending: 0,
    payed: 1,
  }

  class << self
    def create_pending_payment_for_all_members
      transaction do
        Member.all.find_each(&:create_pending_payment)
      end
    end
  end
end

app/models/updates_payment_statuses.rb
class UpdatesPaymentStatuses
  def initialize(payed_payment_params:)
    @payed_payment_params = payed_payment_params
      .to_unsafe_hash
      .transform_keys(&:to_i)
  end

  def update_payments
    payments.each do |payment|
      update_payment(payment)
    end
  end

  def payments
    @payments ||= Payment.find(@payed_payment_params.keys)
  end

  private

  def update_payment(payment)
    status_param = @payed_payment_params.fetch(payment.id)

    if status_param == "1"
      payment.payed!
    else
      raise "TODO"
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  include Clearance::User
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller

  protect_from_forgery with: :exception
end

app/controllers/concerns/http_basic_auth.rb
module HttpBasicAuth
  extend ActiveSupport::Concern

  included do
    http_basic_authenticate_with(
      name: ENV.fetch("BASIC_AUTH_USERNAME"),
      password: ENV.fetch("BASIC_AUTH_PASSWORD"),
    )
  end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  def index
    @members = Member.all

    if params[:filters].present?
      @members = apply_filters(@members)
    end

    @members = PaginatedRelation.new(
      relation: @members,
      per_page: 20,
    ).page(params[:page].try(:to_i) || 0)
  end

  def show
    @member = Member.find(params[:id])
  end

  def new
    @member = Member.new
  end

  def create
    member_params = params.require(:member).permit(
      :first_name,
      :middle_name,
      :last_name,
      :date_of_birth,
      :membership_type,
      :email,
      :admission_date,
    )

    @member = Member.new(member_params)

    if @member.save
      flash.notice = "Member created"
      redirect_to @member
    else
      flash.alert = "Something went wrong"
      render :new
    end
  end

  private

  def apply_filters(members)
    MemberFilters
      .new(filters: params.fetch(:filters))
      .apply_filters(members)
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  def index
    @pending_payments = Payment.pending
    @payed_payments = Payment.payed
  end

  def create
    Payment.create_pending_payment_for_all_members

    redirect_to(
      payments_path,
      notice: "Created #{Member.count} payments",
    )
  end

  def update_statuses
    updates = UpdatesPaymentStatuses.new(
      payed_payment_params: params[:payments],
    )

    updates.update_payments

    redirect_to(
      payments_path,
      notice: "Updated #{updates.payments.size} payments",
    )
  end
end

app/controllers/sessions_controller.rb
class SessionsController < Clearance::SessionsController
  include HttpBasicAuth
end

app/controllers/users_controller.rb
class UsersController < Clearance::UsersController
  include HttpBasicAuth
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Members</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <% if signed_in? %>
      <p>Signed in as <%= current_user.email %></p>
      <%= button_to 'Sign out', sign_out_path, method: :delete %>

      <%= link_to "All members", members_path %>
      <%= link_to "Create new member", new_member_path %>
      <%= link_to "Payments", payments_path %>
    <% else %>
      <%= link_to 'Sign up', sign_up_path %>
      <%= link_to 'Sign in', sign_in_path %>
    <% end %>

    <div id="flash">
      <% flash.each do |key, value| %>
        <div class="flash <%= key %>"><%= value %></div>
      <% end %>
    </div>

    <%= yield %>

  </body>
</html>

app/views/members/index.html.erb
<%= form_tag members_path, method: :get do %>
  <%= fields_for :filters do |filter_fields| %>
    <div>
      <%= filter_fields.label :membership_type %>
      <%=
        filter_fields.select(
          :membership_type,
          options_for_select(
            [["All", nil]] + Member.membership_types.map { |name, value| [name.humanize.titleize, name] },
            params.dig(:filters, :membership_type),
          )
        )
      %>
    </div>

    <div>
      <%= filter_fields.label :minimum_age %>
      <%=
        filter_fields.select(
          :minimum_age,
          options_for_select(
            [["None", nil], ["15", 15], ["25", "25"]],
            params.dig(:filters, :membership_type),
          )
        )
      %>
    </div>

    <div>
      <%= filter_fields.submit "Filter" %>
    </div>
  <% end %>
<% end %>

<% if @members.present? %>
  <p>
    <%= @members.size %> matching <%= "member".pluralize(@members.size) %>
  </p>

  <ul class="members-list">
    <% @members.each do |member| %>
      <li>
        <%= link_to member.name, member %>
      </li>
    <% end %>
  </ul>

  <div class="pagination">
    <%=
      link_to_if(
        @members.previous_page?,
        "Previous page",
        members_path(
          page: @members.index_of_previous_page,
          filters: params[:filters].try(:to_unsafe_hash),
        ),
      )
    %>
    <%=
      link_to_if(
        @members.next_page?,
        "Next page",
        members_path(
          page: @members.index_of_next_page,
          filters: params[:filters].try(:to_unsafe_hash),
        ),
      )
    %>
    <p>
      Page <%= @members.current_page_index + 1 %> of <%= @members.total_number_of_pages %>
    </p>
  </div>
<% else %>
  <p>There are no members yet 😭</p>
<% end %>

app/views/members/new.html.erb
<% if @member.errors.any? %>
  <ul>
    <% @member.errors.full_messages.each do |error| %>
      <li><%= error %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for @member do |form| %>
  <div>
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>
  </div>

  <div>
    <%= form.label :middle_name %>
    <%= form.text_field :middle_name %>
  </div>

  <div>
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </div>

  <div>
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :date_of_birth %>
    <%= form.date_select :date_of_birth %>
  </div>

  <div>
    <%= form.label :admission_date %>
    <%= form.date_select :admission_date %>
  </div>

  <div>
    <%= form.label :membership_type %>
    <%= form.select :membership_type, options_for_select(Member.membership_types.map { |name, value| [name.humanize.titleize, name] }) %>
  </div>

  <div>
    <%= form.submit "Create member" %>
  </div>
<% end %>

app/views/members/show.html.erb
<h1>
  <%= @member.name %>
</h1>

<dl>
  <%
    [
      ["First name", :first_name],
      ["Middle name", :middle_name],
      ["Last name", :last_name],
      ["Membership type", ->(member) { member.membership_type.titleize }],
      ["Date of Birth", :date_of_birth],
      ["Nationality", :nationality],
      ["Address", :address],
      ["Zip", :zip],
      ["City", :city],
      ["Phone", :phone],
      ["Email", :email],
      ["CPR", :cpr],
      ["Dad's phone", :dad_phone],
      ["Mom's phone", :mom_phone],
      ["Dad's email", :dad_email],
      ["Mom's email", :mom_email],
      ["Admission date", :admission_date],
    ].each do |humanreadable_field_value, field|
  %>
    <dt><%= humanreadable_field_value %></dt>

    <%
        value = if field.respond_to?(:call)
                  field.call @member
                else
                  @member.send(field)
                end

        if value.nil?
          value = "-"
        end
    %>

    <dd><%= value %></dd>
  <% end %>
</dl>

app/views/payments/index.html.erb
<%= link_to "Create pending payments for all members", payments_path, method: :post, data: { confirm: "Sure?" } %>

<h1>Pending payments</h1>

<div class="pending-payments">
  <% if @pending_payments.present? %>
    <%= form_tag update_statuses_payments_path, method: :patch do %>
      <ul>
        <% @pending_payments.each do |payment| %>
          <li class="pending-payment">
            <%= check_box_tag "payments[#{payment.id}]" %>
            <%= label_tag "payments[#{payment.id}]", payment.member.name %>
          </li>
        <% end %>
      </ul>

      <%= submit_tag "Save payment statuses" %>
    <% end %>
  <% else %>
    No pending payments 👍
  <% end %>
</div>

<h1>Payed payments</h1>

<div class="payed-payments">
  <% if @payed_payments.present? %>
    <ul>
      <% @payed_payments.each do |payment| %>
        <li class="payed-payment">
          <%= payment.member.name %>
        </li>
      <% end %>
    </ul>
  <% else %>
    No payed payments 👎
  <% end %>
</div>

app/views/welcome/index.html.erb
<h1>
  Members
</h1>